### ISSUE TITLE
SuperMicro entities

### ISSUE THREAD

**Issue by kimsvane** [ateodorescu/home-assistant-ipmi#42]
Hey all 

Im having issues with the IPMI connector or tool. 
It only discovers 2 entities, and this has been able to show wattage and alot more, but it does not anymore. 

What would you need to help ?

**Comment by ateodorescu** [comment]
If the server is shutdown when ipmi starts then you don't get all sensors. Later on, when the server starts, the new sensors are not visible. This is because there are some issues that I do not know how to fix with this https://github.com/ateodorescu/home-assistant-ipmi/blob/c8576bcf652c4dc84261c098c135c121c57a5764/custom_components/ipmi/sensor.py#L101

I am creating a listener for an event that is fired when sensors are fetched:
https://github.com/ateodorescu/home-assistant-ipmi/blob/c8576bcf652c4dc84261c098c135c121c57a5764/custom_components/ipmi/sensor.py#L104

Unfortunately the listener callback fails and I don't really understand why it fails in latest versions but it was working fine few versions of HASS ago. If someone could help out with this then ping me or create a PR.

**Comment by ateodorescu** [comment]
@kimsvane Did you try the latest version? Is that fixed?

**Comment by kimsvane** [comment]
Yes, embarrassing enough I forgot that I did a manual install. 
So when I tried to check for updates in HACS, I could not see it in there. 

So I just installed it from HACS and now it works.
